vanity = "0x00"
validators = ["0x475cc98b5521ab2a1335683e7567c8048bfe79ed",
"0x07d8299de61faed3686ba4c4e6c3b9083d7e2371",
"0x4fe035ce99af680d89e2c4d73aca01dbfc1bd2fd",
"0xdc421209441a754f79c4a4ecd2b49c935aad0312"]